import { BasicColor, type MaybeColor } from "../color";
import { Attribute, Bit, type UnderlineStyle } from "./attributes";

export const BASIC_COLOR_TO_FOREGROUND_BIT: Record<BasicColor, Bit> = {
  [BasicColor.Black]: Bit.BlackForegroundColor,
  [BasicColor.Red]: Bit.RedForegroundColor,
  [BasicColor.Green]: Bit.GreenForegroundColor,
  [BasicColor.Yellow]: Bit.YellowForegroundColor,
  [BasicColor.Blue]: Bit.BlueForegroundColor,
  [BasicColor.Magenta]: Bit.MagentaForegroundColor,
  [BasicColor.Cyan]: Bit.CyanForegroundColor,
  [BasicColor.White]: Bit.WhiteForegroundColor,
  [BasicColor.BrightBlack]: Bit.BrightBlackForegroundColor,
  [BasicColor.BrightRed]: Bit.BrightRedForegroundColor,
  [BasicColor.BrightGreen]: Bit.BrightGreenForegroundColor,
  [BasicColor.BrightYellow]: Bit.BrightYellowForegroundColor,
  [BasicColor.BrightBlue]: Bit.BrightBlueForegroundColor,
  [BasicColor.BrightMagenta]: Bit.BrightMagentaForegroundColor,
  [BasicColor.BrightCyan]: Bit.BrightCyanForegroundColor,
  [BasicColor.BrightWhite]: Bit.BrightWhiteForegroundColor,
};

export const BASIC_COLOR_TO_BACKGROUND_BIT: Record<BasicColor, Bit> = {
  [BasicColor.Black]: Bit.BlackBackgroundColor,
  [BasicColor.Red]: Bit.RedBackgroundColor,
  [BasicColor.Green]: Bit.GreenBackgroundColor,
  [BasicColor.Yellow]: Bit.YellowBackgroundColor,
  [BasicColor.Blue]: Bit.BlueBackgroundColor,
  [BasicColor.Magenta]: Bit.MagentaBackgroundColor,
  [BasicColor.Cyan]: Bit.CyanBackgroundColor,
  [BasicColor.White]: Bit.WhiteBackgroundColor,
  [BasicColor.BrightBlack]: Bit.BrightBlackBackgroundColor,
  [BasicColor.BrightRed]: Bit.BrightRedBackgroundColor,
  [BasicColor.BrightGreen]: Bit.BrightGreenBackgroundColor,
  [BasicColor.BrightYellow]: Bit.BrightYellowBackgroundColor,
  [BasicColor.BrightBlue]: Bit.BrightBlueBackgroundColor,
  [BasicColor.BrightMagenta]: Bit.BrightMagentaBackgroundColor,
  [BasicColor.BrightCyan]: Bit.BrightCyanBackgroundColor,
  [BasicColor.BrightWhite]: Bit.BrightWhiteBackgroundColor,
};
export const COLOR_TO_BIT: Record<BasicColor, Bit> = {
  [BasicColor.Black]: Bit.BlackForegroundColor,
  [BasicColor.Red]: Bit.RedForegroundColor,
  [BasicColor.Green]: Bit.GreenForegroundColor,
  [BasicColor.Yellow]: Bit.YellowForegroundColor,
  [BasicColor.Blue]: Bit.BlueForegroundColor,
  [BasicColor.Magenta]: Bit.MagentaForegroundColor,
  [BasicColor.Cyan]: Bit.CyanForegroundColor,
  [BasicColor.White]: Bit.WhiteForegroundColor,
  [BasicColor.BrightBlack]: Bit.BrightBlackForegroundColor,
  [BasicColor.BrightRed]: Bit.BrightRedForegroundColor,
  [BasicColor.BrightGreen]: Bit.BrightGreenForegroundColor,
  [BasicColor.BrightYellow]: Bit.BrightYellowForegroundColor,
  [BasicColor.BrightBlue]: Bit.BrightBlueForegroundColor,
  [BasicColor.BrightMagenta]: Bit.BrightMagentaForegroundColor,
  [BasicColor.BrightCyan]: Bit.BrightCyanForegroundColor,
  [BasicColor.BrightWhite]: Bit.BrightWhiteForegroundColor,
};

/** Bit <-> Attribute */
export const BIT_TO_ATTRIBUTE = Object.freeze({
  [Bit.Reset]: Attribute.Reset,
  [Bit.Bold]: Attribute.Bold,
  [Bit.Faint]: Attribute.Faint,
  [Bit.Italic]: Attribute.Italic,
  [Bit.Underline]: Attribute.Underline,
  [Bit.Blink]: Attribute.Blink,
  [Bit.RapidBlink]: Attribute.RapidBlink,
  [Bit.Reverse]: Attribute.Reverse,
  [Bit.Conceal]: Attribute.Conceal,
  [Bit.Strikethrough]: Attribute.Strikethrough,
  [Bit.NormalIntensity]: Attribute.NormalIntensity,
  [Bit.NoItalic]: Attribute.NoItalic,
  [Bit.NoUnderline]: Attribute.NoUnderline,
  [Bit.NoBlink]: Attribute.NoBlink,
  [Bit.NoReverse]: Attribute.NoReverse,
  [Bit.NoConceal]: Attribute.NoConceal,
  [Bit.NoStrikethrough]: Attribute.NoStrikethrough,
  [Bit.BlackForegroundColor]: Attribute.BlackForegroundColor,
  [Bit.RedForegroundColor]: Attribute.RedForegroundColor,
  [Bit.GreenForegroundColor]: Attribute.GreenForegroundColor,
  [Bit.YellowForegroundColor]: Attribute.YellowForegroundColor,
  [Bit.BlueForegroundColor]: Attribute.BlueForegroundColor,
  [Bit.MagentaForegroundColor]: Attribute.MagentaForegroundColor,
  [Bit.CyanForegroundColor]: Attribute.CyanForegroundColor,
  [Bit.WhiteForegroundColor]: Attribute.WhiteForegroundColor,
  [Bit.ExtendedForegroundColor]: Attribute.ExtendedForegroundColor,
  [Bit.DefaultForegroundColor]: Attribute.DefaultForegroundColor,
  [Bit.BlackBackgroundColor]: Attribute.BlackBackgroundColor,
  [Bit.RedBackgroundColor]: Attribute.RedBackgroundColor,
  [Bit.GreenBackgroundColor]: Attribute.GreenBackgroundColor,
  [Bit.YellowBackgroundColor]: Attribute.YellowBackgroundColor,
  [Bit.BlueBackgroundColor]: Attribute.BlueBackgroundColor,
  [Bit.MagentaBackgroundColor]: Attribute.MagentaBackgroundColor,
  [Bit.CyanBackgroundColor]: Attribute.CyanBackgroundColor,
  [Bit.WhiteBackgroundColor]: Attribute.WhiteBackgroundColor,
  [Bit.ExtendedBackgroundColor]: Attribute.ExtendedBackgroundColor,
  [Bit.DefaultBackgroundColor]: Attribute.DefaultBackgroundColor,
  [Bit.ExtendedUnderlineColor]: Attribute.ExtendedUnderlineColor,
  [Bit.DefaultUnderlineColor]: Attribute.DefaultUnderlineColor,
  [Bit.BrightBlackForegroundColor]: Attribute.BrightBlackForegroundColor,
  [Bit.BrightRedForegroundColor]: Attribute.BrightRedForegroundColor,
  [Bit.BrightGreenForegroundColor]: Attribute.BrightGreenForegroundColor,
  [Bit.BrightYellowForegroundColor]: Attribute.BrightYellowForegroundColor,
  [Bit.BrightBlueForegroundColor]: Attribute.BrightBlueForegroundColor,
  [Bit.BrightMagentaForegroundColor]: Attribute.BrightMagentaForegroundColor,
  [Bit.BrightCyanForegroundColor]: Attribute.BrightCyanForegroundColor,
  [Bit.BrightWhiteForegroundColor]: Attribute.BrightWhiteForegroundColor,
  [Bit.BrightBlackBackgroundColor]: Attribute.BrightBlackBackgroundColor,
  [Bit.BrightRedBackgroundColor]: Attribute.BrightRedBackgroundColor,
  [Bit.BrightGreenBackgroundColor]: Attribute.BrightGreenBackgroundColor,
  [Bit.BrightYellowBackgroundColor]: Attribute.BrightYellowBackgroundColor,
  [Bit.BrightBlueBackgroundColor]: Attribute.BrightBlueBackgroundColor,
  [Bit.BrightMagentaBackgroundColor]: Attribute.BrightMagentaBackgroundColor,
  [Bit.BrightCyanBackgroundColor]: Attribute.BrightCyanBackgroundColor,
  [Bit.BrightWhiteBackgroundColor]: Attribute.BrightWhiteBackgroundColor,
});
/** Attribute <-> Bit */
export const ATTRIBUTE_TO_BIT = Object.freeze({
  [Attribute.Reset]: Bit.Reset,
  [Attribute.Bold]: Bit.Bold,
  [Attribute.Faint]: Bit.Faint,
  [Attribute.Italic]: Bit.Italic,
  [Attribute.Underline]: Bit.Underline,
  [Attribute.Blink]: Bit.Blink,
  [Attribute.RapidBlink]: Bit.RapidBlink,
  [Attribute.Reverse]: Bit.Reverse,
  [Attribute.Conceal]: Bit.Conceal,
  [Attribute.Strikethrough]: Bit.Strikethrough,
  [Attribute.NormalIntensity]: Bit.NormalIntensity,
  [Attribute.NoItalic]: Bit.NoItalic,
  [Attribute.NoUnderline]: Bit.NoUnderline,
  [Attribute.NoBlink]: Bit.NoBlink,
  [Attribute.NoReverse]: Bit.NoReverse,
  [Attribute.NoConceal]: Bit.NoConceal,
  [Attribute.NoStrikethrough]: Bit.NoStrikethrough,
  [Attribute.BlackForegroundColor]: Bit.BlackForegroundColor,
  [Attribute.RedForegroundColor]: Bit.RedForegroundColor,
  [Attribute.GreenForegroundColor]: Bit.GreenForegroundColor,
  [Attribute.YellowForegroundColor]: Bit.YellowForegroundColor,
  [Attribute.BlueForegroundColor]: Bit.BlueForegroundColor,
  [Attribute.MagentaForegroundColor]: Bit.MagentaForegroundColor,
  [Attribute.CyanForegroundColor]: Bit.CyanForegroundColor,
  [Attribute.WhiteForegroundColor]: Bit.WhiteForegroundColor,
  [Attribute.ExtendedForegroundColor]: Bit.ExtendedForegroundColor,
  [Attribute.DefaultForegroundColor]: Bit.DefaultForegroundColor,
  [Attribute.BlackBackgroundColor]: Bit.BlackBackgroundColor,
  [Attribute.RedBackgroundColor]: Bit.RedBackgroundColor,
  [Attribute.GreenBackgroundColor]: Bit.GreenBackgroundColor,
  [Attribute.YellowBackgroundColor]: Bit.YellowBackgroundColor,
  [Attribute.BlueBackgroundColor]: Bit.BlueBackgroundColor,
  [Attribute.MagentaBackgroundColor]: Bit.MagentaBackgroundColor,
  [Attribute.CyanBackgroundColor]: Bit.CyanBackgroundColor,
  [Attribute.WhiteBackgroundColor]: Bit.WhiteBackgroundColor,
  [Attribute.ExtendedBackgroundColor]: Bit.ExtendedBackgroundColor,
  [Attribute.DefaultBackgroundColor]: Bit.DefaultBackgroundColor,
  [Attribute.ExtendedUnderlineColor]: Bit.ExtendedUnderlineColor,
  [Attribute.DefaultUnderlineColor]: Bit.DefaultUnderlineColor,
  [Attribute.BrightBlackForegroundColor]: Bit.BrightBlackForegroundColor,
  [Attribute.BrightRedForegroundColor]: Bit.BrightRedForegroundColor,
  [Attribute.BrightGreenForegroundColor]: Bit.BrightGreenForegroundColor,
  [Attribute.BrightYellowForegroundColor]: Bit.BrightYellowForegroundColor,
  [Attribute.BrightBlueForegroundColor]: Bit.BrightBlueForegroundColor,
  [Attribute.BrightMagentaForegroundColor]: Bit.BrightMagentaForegroundColor,
  [Attribute.BrightCyanForegroundColor]: Bit.BrightCyanForegroundColor,
  [Attribute.BrightWhiteForegroundColor]: Bit.BrightWhiteForegroundColor,
  [Attribute.BrightBlackBackgroundColor]: Bit.BrightBlackBackgroundColor,
  [Attribute.BrightRedBackgroundColor]: Bit.BrightRedBackgroundColor,
  [Attribute.BrightGreenBackgroundColor]: Bit.BrightGreenBackgroundColor,
  [Attribute.BrightYellowBackgroundColor]: Bit.BrightYellowBackgroundColor,
  [Attribute.BrightBlueBackgroundColor]: Bit.BrightBlueBackgroundColor,
  [Attribute.BrightMagentaBackgroundColor]: Bit.BrightMagentaBackgroundColor,
  [Attribute.BrightCyanBackgroundColor]: Bit.BrightCyanBackgroundColor,
  [Attribute.BrightWhiteBackgroundColor]: Bit.BrightWhiteBackgroundColor,
});

/**
 * Attribute <-> Property
 *
 * @remarks There is no direct background, foreground and underline attribute, so there is no direct mapping either.
 */
export const ATTRIBUTE_TO_PROP = Object.freeze({
  [Attribute.Reset]: "reset",
  [Attribute.Bold]: "bold",
  [Attribute.Faint]: "faint",
  [Attribute.Italic]: "italic",
  [Attribute.Underline]: "underline",
  [Attribute.Blink]: "blink",
  [Attribute.RapidBlink]: "rapidBlink",
  [Attribute.Reverse]: "reverse",
  [Attribute.Conceal]: "conceal",
  [Attribute.Strikethrough]: "strikethrough",
  [Attribute.NormalIntensity]: "normalIntensity",
  [Attribute.NoItalic]: "noItalic",
  [Attribute.NoUnderline]: "noUnderline",
  [Attribute.NoBlink]: "noBlink",
  [Attribute.NoReverse]: "noReverse",
  [Attribute.NoConceal]: "noConceal",
  [Attribute.NoStrikethrough]: "noStrikethrough",
  [Attribute.DefaultForegroundColor]: "defaultForegroundColor",
  [Attribute.DefaultBackgroundColor]: "defaultBackgroundColor",
  [Attribute.DefaultUnderlineColor]: "defaultUnderlineColor",
});
/**
 * Property <-> Attribute
 *
 * @remarks There is no direct background, foreground and underline attribute, so there is no direct mapping either.
 */
export const PROP_TO_ATTRIBUTE = Object.freeze({
  reset: Attribute.Reset,
  bold: Attribute.Bold,
  faint: Attribute.Faint,
  italic: Attribute.Italic,
  underline: Attribute.Underline,
  blink: Attribute.Blink,
  rapidBlink: Attribute.RapidBlink,
  reverse: Attribute.Reverse,
  conceal: Attribute.Conceal,
  strikethrough: Attribute.Strikethrough,
  normalIntensity: Attribute.NormalIntensity,
  noItalic: Attribute.NoItalic,
  noUnderline: Attribute.NoUnderline,
  noBlink: Attribute.NoBlink,
  noReverse: Attribute.NoReverse,
  noConceal: Attribute.NoConceal,
  noStrikethrough: Attribute.NoStrikethrough,
  defaultForegroundColor: Attribute.DefaultForegroundColor,
  defaultBackgroundColor: Attribute.DefaultBackgroundColor,
  defaultUnderlineColor: Attribute.DefaultUnderlineColor,
});

/**
 * AttributeProps defines attributes in a property format.
 */
export type AttributesProps = {
  [K in keyof typeof PROP_TO_ATTRIBUTE]: boolean;
} & {
  backgroundColor: MaybeColor;
  foregroundColor: MaybeColor;
  underlineColor: MaybeColor;
  underlineStyle: UnderlineStyle;
};
